FROM pihole/pihole:latest


RUN apt-get -y update
RUN apt-get install python3 -y
# RUN apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev
# RUN wget https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz
# tar xzf Python-3.8.2.tgz
# cd Python-3.8.2
# ./configure --enable-optimizations
# make altinstall

#RUN apt-get install git python3.8 -y

#https://github.com/anudeepND/whitelist#for-docker-installation-with-python3-support
RUN git clone https://github.com/anudeepND/whitelist.git
USER root
RUN python3 whitelist/scripts/whitelist.py
RUN ./whitelist/scripts/referral.sh
COPY ./adlist.json /
COPY ./installAdLists.py /
#RUN sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address,enabled) VALUES ('https://v.firebog.net/hosts/lists.php?type=tick',1)"
RUN python3 installAdLists.py


SHELL ["/bin/bash", "-c"]